### ISSUE TITLE
lost important changes

### ISSUE THREAD

**Issue by manwar** [abbypan/Simple-IPInfo#3]
Hi @abbypan ,

Just for you information, in case you missed it.

I noticed the following commit, lost the changes from Neil Bowers PR.
https://github.com/abbypan/Simple-IPInfo/commit/7e0183555810c0790816d48d42662e32cb203934

     - use 5.008;
     - use strict;
     - use warnings;
     - use parent 'Exporter';
     - our @EXPORT = qw(
     + require Exporter;
     + @ISA    = qw(Exporter);
     + @EXPORT = qw(
           get_ip_loc

Here is the commit from Neil Bowers PR:
https://github.com/abbypan/Simple-IPInfo/commit/30f220877cb3aadc2f66af23b371f44c3f1bafae#diff-b42b1740ffcebc1a50b51b1340b76373

Many Thanks,
Best Regards,
Mohammad S Anwar

**Comment by abbypan** [comment]
thanks a lot, fixed now
